### ISSUE TITLE
Dyslexic mode font is missing, changes to default serif font instead

### ISSUE THREAD

**Issue by OrniiDiien** [crabber-net/crabber#141]
I know this will probably be fixed with everything else related to new database problems, but I figured I'd put this here

**Comment by jakeledoux** [comment]
I've heard a couple people say this but I cannot reproduce it. What happens if you clear your cache and force reload?

The font links served are valid. Are there any CORS problems coming up in your debug console perhaps?

**Comment by xpyxel** [comment]
> I've heard a couple people say this but I cannot reproduce it. What happens if you clear your cache and force reload?
> 
> The font links served are valid. Are there any CORS problems !oming up in your debug console perhaps?

Yeah it gives CORS errors on my end 

![screenshot](https://egg.lgbt/i/c8a20nr7.png)

**Comment by jakeledoux** [comment]
This is hard to test because it works fine on my end. I changed some header stuff, does it work now?

**Comment by xpyxel** [comment]
> This is hard to test because it works fine on my end. I changed some header stuff, does it work now?

Doesn't look like it, no, god I hate CORS.

**Comment by xpyxel** [comment]
CORS is a server side issue, i think you need to add a `Access-Control-Allow-Origin: *` header to the side serving `crabber.net`.

**Comment by jakeledoux** [comment]
I know. I was messing around with the headers but Apache2 is a pathetic server and rather than continue that path I've switched the links so that flask serves the fonts. This should now be fixed.

I really can't wait to get the servers onto nginx...
