### ISSUE TITLE
Change the mention icon in notifications to a colour other than red

### ISSUE THREAD

**Issue by OrniiDiien** [crabber-net/crabber#145]
**Is your feature request related to a problem? Please describe.**
I just tend to mentally blend together people liking my molts and people mentioning me in notifications so

**Describe the solution you'd like**
See title. Of course a colour other than the ones that have already been used. Maybe purple, or yellow?

**Comment by jakeledoux** [comment]
Good point.

> Of course a colour other than the ones that have already been used

What about using the same blue as the reply notifications since mentions and replies are fairly similar?

**Comment by xpyxel** [comment]
> Good point.
> 
> > Of course a colour other than the ones that have already been used
> 
> What about using the same blue as the reply notifications since mentions and replies are fairly similar?

Sounds good to me, honestly.

**Comment by OrniiDiien** [comment]
> > Good point.
> > > Of course a colour other than the ones that have already been used
> > 
> > 
> > What about using the same blue as the reply notifications since mentions and replies are fairly similar?
> 
> Sounds good to me, honestly.

yeah that could work!
