### ISSUE TITLE
Plural-friendly profile feature

### ISSUE THREAD

**Issue by AiNaKaGames** [crabber-net/crabber#149]
Because of Crabber's prominently large and still growing plural community demographic, i think it'd be a great idea to add plural-friendly features, like "alt profiles" on one account, almost like discord's pluralkit bot, so people can post with a different name/pfp on the same account, possibly while writing the post, they can choose a profile to post it as.

**Comment by xpyxel** [comment]
Going to convert this to a discussion, as I believe this needs to be discussed a bit more before any decisions are made.
