### ISSUE TITLE
All Icons Disappeared

### ISSUE THREAD

**Issue by pepiscola** [crabber-net/crabber#156]
All icons under molts & for the different tabs are blank right now.

**Comment by xpyxel** [comment]
can't reproduce this? [screenshot](https://egg.lgbt/i/kynvpz4b.png)

**Comment by pepiscola** [comment]
![Screenshot_20211106-162513](https://user-images.githubusercontent.com/93842453/140624337-c4967d7f-244f-4520-b0f9-b8be9072efc1.jpg)
huh, here's a screenshot from my end. im using an android OnePlus & the firefox browser.

**Comment by xpyxel** [comment]
Can't reproduce with the same settings (light + spooky + comic sans), wonder if this is a firefox specific issue

**Comment by xpyxel** [comment]
i'm able to reproduce on firefox mobile, though i'm unsure why it's happening.

**Comment by xpyxel** [comment]
Was able to find what caused this, alerted jake.

**Comment by xpyxel** [comment]
This should be fixed.
