### ISSUE TITLE
Longer molts get the last few characters removed after posting?

### ISSUE THREAD

**Issue by OrniiDiien** [crabber-net/crabber#158]
**Describe the bug**
If you make a molt near to or at the character limit WITH PARAGRAPH BREAKS, the last few characters disappear when the molt is posted. Editing the molt to add things back in works fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/63260365/140652892-841026b0-25bb-4e83-bc38-fa4d8bc2b465.png)
![image](https://user-images.githubusercontent.com/63260365/140652900-7005a347-88a7-48e9-97ef-57e364fd4ff6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi (Chromium)
 - Version: 3.7.2218.52

**Comment by jakeledoux** [comment]
Yikes. Looks like Python and JavaScript are disagreeing on the length of the string. We'll look into this.

**Comment by jakeledoux** [comment]
The issue was that the submitted content used DOS-style line-endings. That meant that each newline was denoted by both the `\r` and `\n` characters as opposed to just `\n`, causing Python to count newlines twice and trim the remaining characters.
