### ISSUE TITLE
Rename Wild West to something Ocean related

### ISSUE THREAD

**Issue by blazingfennec** [crabber-net/crabber#183]
I really like the Wild West section on here, but it doesn't make too much sense thematically.
I propose renaming it to something Ocean related to help hit the crab theme better.
A few names I've considered are "Open Ocean" and "Drift Stream"

**Comment by xpyxel** [comment]
I'll poke @jakeledoux with this and get his opinion on it.

**Comment by jakeledoux** [comment]
Sorry no. The Wild West has solidified as one of Crabber's most loved features over the past few years and the name is part of that. Sure it's not nautically-themed but not everything on Twitter is bird themed either. If we do an ocean/solarized color scheme sometime then we'll rename /wild within that context, but as it stands, Wild West is not going anywhere.
